language: cpp
dist: bionic
os:
- linux

compiler:
  - gcc
  - clang
  
before_script:
  - mkdir build
  - cd build
  - cmake -DCUNITTESTS_FLAGS=ON -DCUNITTESTS_TESTING=ON ..

script:
  - make && make test
